openapi: 3.0.3

info:
  title: Kitchen API
  description: API that allows to manage the production of food orders in the kitchen
  version: 1.0.0

servers:
  - url: http://127.0.0.1:5000
    description: URL for local development and testing
  - url: https://coffeemesh.com
    description: main production server
  - url: https://coffeemesh-staging.com
    description: staging server for testing purposes only

paths:
  /kitchen/schedules:
    get:
      summary: Returns a list of orders scheduled for creation in the kitchen
      tags:
        - kitchen
      parameters:
        - name: progress
          in: query
          description: >-
            Whether the order is in progress or not.
            In progress means it's in production in the kitchen.
          required: false
          schema:
            type: boolean
        - name: limit
          in: query
          required: false
          schema:
            type: integer
        - name: since
          in: query
          required: false
          schema:
            type: string
            format: 'date-time'
      responses:
        '200':
          description: A list of scheduled food orders
          content:
            application/json:
              schema:
                additionalProperties: false
                type: object
                properties:
                  schedules:
                    type: array
                    items:
                      $ref: '#/components/schemas/GetScheduledOrderSchema'

    post:
      summary: Schedules a food order for production
      tags:
        - kitchen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduleOrderSchema'
      responses:
        '201':
          description: A JSON representation of the scheduled food order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetScheduledOrderSchema'

  /kitchen/schedules/{schedule_id}:
    parameters:
      - in: path
        name: schedule_id
        required: true
        schema:
          type: string
          format: uuid
    get:
      summary: Returns the status and details of a scheduled food order
      tags:
        - kitchen
      responses:
        '200':
          description: A JSON representation of a scheduled food order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleOrderSchema'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      summary: Updates an existing scheduled food order
      tags:
        - kitchen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduleOrderSchema'
      responses:
        '200':
          description: A JSON representation of a scheduled food order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetScheduledOrderSchema'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: Deletes an existing food order
      tags:
        - kitchen
      responses:
        '204':
          description: The food order was deleted successfully

  /kitchen/schedules/{schedule_id}/status:
    parameters:
      - in: path
        name: schedule_id
        required: true
        schema:
          type: string
          format: uuid
    get:
      summary: Returns the status of a scheduled food order
      tags:
        - kitchen
      responses:
        '200':
          description: A JSON representation of a scheduled food order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleStatusSchema'
        '404':
          $ref: '#/components/responses/NotFound'

  /kitchen/schedules/{schedule_id}/cancel:
    parameters:
      - in: path
        name: schedule_id
        required: true
        schema:
          type: string
          format: uuid
    post:
      summary: Cancels a scheduled food order
      tags:
        - kitchen
      responses:
        '200':
          description: A JSON representation of a scheduled food order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleOrderSchema'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  responses:
    NotFound:
      description: The specified resource was not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    Error:
      type: object
      properties:
        error:
          type: string

    OrderItemSchema:
      additionalProperties: false
      type: object
      required:
        - food
        - quantity
        - size
      properties:
        food:
          type: string
        size:
          type: string
          enum:
            - small
            - medium
            - big
        quantity:
          type: integer
          minimum: 1

    ScheduleOrderSchema:
      type: object
      additionalProperties: false
      required:
        - order
      properties:
        order:
          type: array
          items:
            $ref: '#/components/schemas/OrderItemSchema'

    GetScheduledOrderSchema:
      type: object
      additionalProperties: false
      required:
        - id
        - order
        - scheduled
        - status
      properties:
        id:
          type: string
          format: uuid
        scheduled:
          type: string
          format: 'date-time'
        status:
          type: string
          enum:
            - pending
            - progress
            - cancelled
            - finished
        order:
          type: array
          items:
            $ref: '#/components/schemas/OrderItemSchema'

    ScheduleStatusSchema:
      type: object
      additionalProperties: false
      required:
        - status
      properties:
        status:
          type: string
          enum:
            - pending
            - progress
            - cancelled
            - finished
