# generated by datamodel-codegen:
#   filename:  oas.yaml
#   timestamp: 2024-03-03T15:41:46+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional, Union
from uuid import UUID

from pydantic import BaseModel, Field, conint


class Error(BaseModel):
    detail: Union[str, List]


class Size(Enum):
    small = 'small'
    medium = 'medium'
    big = 'big'


class OrderItemSchema(BaseModel):
    product: str
    size: Size
    quantity: Optional[conint(ge=1, le=1000000)] = 1


class CreateOrderSchema(BaseModel):
    order: List[OrderItemSchema] = Field(..., min_items=1)


class Status(Enum):
    created = 'created'
    paid = 'paid'
    progress = 'progress'
    cancelled = 'cancelled'
    dispatched = 'dispatched'
    delivered = 'delivered'


class GetOrderSchema(BaseModel):
    id: UUID
    created: datetime
    status: Status
    order: List[OrderItemSchema] = Field(..., min_items=1)


class GetOrdersSchema(BaseModel):
    orders: List[GetOrderSchema]
